server:
port: 8080
spring:
datasource:
url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/pmdb}
username: ${DB_USER:postgres}
password: ${DB_PASS:postgres}
jpa:
hibernate:
ddl-auto: update
show-sql: true
jwt:
secret: ${JWT_SECRET:change-me-in-prod}
expiration-ms: 86400000
